
sonar.projectKey=gestion-rh-frontend
sonar.projectName=Rhconnect
sonar.projectVersion=1.0


sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.inclusions=src/**/*.{ts,tsx,js}
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/datta-able-free/lcov.info

sonar.typescript.tsconfigPath=tsconfig.json


