# Generated by Django 5.1.7 on 2025-04-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='uploads/candidatures_cv/'),
        ),
    ]
