# Generated by Django 5.1.7 on 2025-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0002_candidature_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='competences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
