# Generated by Django 5.1.7 on 2025-04-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0003_offreemploi_competences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='cv',
        ),
    ]
