# Generated by Django 5.0.7 on 2025-05-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0004_remove_candidature_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('licence', 'Licence'), ('master', 'Master'), ('ingenieur', 'Ingénieur'), ('doctorat', 'Doctorat'), ('expert', 'Expert'), ('recherche', 'Chercheur/Recherche')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='niveau_experience',
            field=models.CharField(blank=True, choices=[('aucune', 'Aucune expérience'), ('moins_1_an', "Moins d'un an"), ('entre_1_2_ans', 'Entre 1 et 2 ans'), ('entre_2_5_ans', 'Entre 2 et 5 ans'), ('entre_5_10_ans', 'Entre 5 et 10 ans'), ('plus_10_ans', 'Plus que 10 ans')], max_length=20, null=True),
        ),
    ]
