# Generated by Django 5.0.7 on 2025-05-14 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0005_candidat_date_naissance_candidat_niveau_etude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='date_publication',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='disponibilite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='langues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='niveau_etude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='type_poste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('licence', 'Licence'), ('master', 'Master'), ('ingénierie', 'Ingénierie'), ('doctorat', 'Doctorat'), ('expert', 'Expert'), ('recherche', 'Chercheur/Recherche')], max_length=20, null=True),
        ),
    ]
