# Generated by Django 5.0.7 on 2025-06-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0006_offreemploi_date_publication_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IAModule',
        ),
    ]
