# Generated by Django 5.0.7 on 2025-06-16 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0007_delete_iamodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='est_employe',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste_actuel', models.CharField(max_length=255)),
                ('date_embauche', models.DateField()),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employe_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviCarriereEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_poste', models.CharField(blank=True, max_length=255, null=True)),
                ('nouveau_poste', models.CharField(max_length=255)),
                ('date_changement', models.DateField(auto_now_add=True)),
                ('est_promotion', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='recrutement.employe')),
            ],
        ),
    ]
