# Generated by Django 5.0.7 on 2025-07-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0009_candidature_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participationformation',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='participationformation',
            name='candidat',
        ),
        migrations.AddField(
            model_name='candidature',
            name='label',
            field=models.IntegerField(blank=True, choices=[(0, 'Non pertinent'), (1, 'Pertinent')], null=True),
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
        migrations.DeleteModel(
            name='ParticipationFormation',
        ),
    ]
