# Generated by Django 5.0.7 on 2025-07-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0010_remove_participationformation_formation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='analyse_effectuee',
        ),
        migrations.RemoveField(
            model_name='candidature',
            name='prediction',
        ),
        migrations.RemoveField(
            model_name='candidature',
            name='score_matching',
        ),
    ]
