# Generated by Django 5.0.7 on 2025-08-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0011_remove_candidature_analyse_effectuee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='label',
        ),
        migrations.AddField(
            model_name='candidature',
            name='ai_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
