# Generated by Django 5.0.7 on 2025-08-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0012_remove_candidature_label_candidature_ai_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='label',
            field=models.IntegerField(blank=True, choices=[(0, 'Reject'), (1, 'Hire')], null=True),
        ),
    ]
