# Generated by Django 5.0.7 on 2025-08-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0013_candidature_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='date_naissance',
        ),
        migrations.AddField(
            model_name='candidat',
            name='projects_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidat', 'Candidat'), ('gestionnaire_rh', 'Gestionnaire RH'), ('recruteur', 'Recruteur'), ('employe', 'Employe')], default='candidat', max_length=20),
        ),
    ]
