# Generated by Django 5.0.7 on 2025-08-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0014_remove_candidat_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
