# Generated by Django 5.0.7 on 2025-08-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0015_candidat_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='modalite',
            field=models.CharField(blank=True, choices=[('sur_site', 'Sur site'), ('hybride', 'Hybride'), ('teletravail', 'Télétravail')], max_length=20, null=True),
        ),
    ]
