# Generated by Django 5.0.7 on 2025-08-30 14:48

from django.db import migrations, models
import json, re

def prep_to_json_strings(apps, schema_editor):
    Offre = apps.get_model('recrutement', 'OffreEmploi')
    for o in Offre.objects.all():
        raw = (o.niveau_etude or '').strip()
        if not raw:
            arr = []
        else:
            # coupe sur virgule / point-virgule / slash
            parts = [p.strip() for p in re.split(r'[,;/]+', raw) if p.strip()]
            arr = parts  # si tu veux, mappe ici vers tes codes canoniques
        # ÉCRIRE une chaîne JSON dans le CharField (pour que l'ALTER passe)
        o.niveau_etude = json.dumps(arr, ensure_ascii=False)
        o.save(update_fields=['niveau_etude'])

class Migration(migrations.Migration):
    dependencies = [
        ('recrutement', '0016_offreemploi_modalite'),  # adapte le nom si différent
    ]

    operations = [
        migrations.RunPython(prep_to_json_strings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='offreemploi',
            name='niveau_etude',
            field=models.JSONField(default=list, blank=True),
        ),
    ]
