# Generated by Django 5.0.7 on 2025-08-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0017_alter_offreemploi_niveau_etude'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivicarriereemploye',
            name='notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='suivicarriereemploye',
            name='objectifs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
