# Generated by Django 5.0.7 on 2025-09-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0018_suivicarriereemploye_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='label',
            field=models.CharField(blank=True, choices=[('Hire', 'Hire'), ('Reject', 'Reject')], max_length=16, null=True),
        ),
    ]
