# Generated by Django 5.0.7 on 2025-09-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0019_alter_candidature_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='projects_count',
        ),
    ]
