# Generated by Django 5.0.7 on 2025-09-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0021_alter_offreemploi_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offreemploi',
            name='disponibilite',
            field=models.CharField(blank=True, choices=[('plein_temps', 'Plein temps'), ('mi_temps', 'Mi-temps'), ('temps_partiel_weekend', 'Temps partiel (week-end)'), ('temps_partiel_soir', 'Temps partiel (soir)'), ('horaires_flexibles', 'Horaires flexibles'), ('travail_en_shifts', 'Travail en shifts (2x8/3x8)'), ('saisonnier', 'Saisonnier')], max_length=100, null=True),
        ),
    ]
