# Generated by Django 5.0.7 on 2025-09-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0022_alter_offreemploi_disponibilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offreemploi',
            name='experience',
            field=models.CharField(blank=True, choices=[('aucune', 'Aucune'), ('moins_1_an', 'Moins de 1 an'), ('entre_1_2_ans', '1 à 2 ans'), ('entre_2_5_ans', '2 à 5 ans'), ('entre_5_10_ans', '5 à 10 ans'), ('plus_10_ans', 'Plus de 10 ans')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='titre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='type_poste',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
