# Generated by Django 5.0.7 on 2025-09-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0023_alter_offreemploi_experience_alter_offreemploi_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivicarriereemploye',
            name='objectifs_plan',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
