# Generated by Django 5.0.7 on 2025-09-16 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0024_suivicarriereemploye_objectifs_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suivicarriereemploye',
            name='objectifs',
        ),
    ]
