# Generated by Django 5.0.7 on 2025-09-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0026_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='ai_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidature',
            name='ai_missing',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidature',
            name='ai_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='ai_strengths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
