# Generated by Django 5.0.7 on 2025-10-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0027_candidature_ai_evidence_candidature_ai_missing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='departement',
            field=models.CharField(blank=True, choices=[('AGENCE', 'Agence'), ('FINANCE', 'Finance'), ('COMPTABILITE', 'Comptabilité'), ('CREDIT', 'Crédit'), ('RISQUE', 'Gestion des risques'), ('CONFORMITE', 'Conformité'), ('RH', 'Ressources humaines'), ('INFORMATIQUE', 'Informatique / IT'), ('MARKETING', 'Marketing'), ('COMMERCIAL', 'Commercial / Développement'), ('AUDIT', 'Audit interne'), ('JURIDIQUE', 'Juridique'), ('OPERATION', 'Opérations bancaires'), ('TREASORERIE', 'Trésorerie'), ('STRATEGIE', 'Stratégie et planification'), ('SERVICE_CLIENT', 'Service client'), ('INVESTISSEMENT', 'Banque d’investissement'), ('INTERNATIONAL', 'Commerce international')], max_length=100, null=True, verbose_name='Département'),
        ),
    ]
